[global]
mraauthor=["jotego"]

[parse]
sourcefile="aliens.cpp"

[buttons]
names = [
    { names="Shoot standing,Shoot crouching" }
]

[dipsw]
delete = [ "Unused", "Unknown" ]
# rename = [
#     {  name="Difficulty 1 (Game)", To="Gameplay" },
#     {  name="Difficulty 2 (Strength)", To="Strength" },
#     {  name="Allow Continue", To="Continue" },
# ]

[ROM]
regions = [
    { name="maincpu",  no_offset=true, sequence=[1,0] }, # First 32kB go to $8000, the rest are banked at $6000
    { name="audiocpu",  start="JTFRAME_BA1_START" },
    { name="k007232",   start="PCM_START" },
    { name="k052109",   start="JTFRAME_BA2_START" }, # tiles
    { name="k051960",   start="JTFRAME_BA3_START" }, # sprites
    { name="proms",     start="JTFRAME_PROM_START" } # last one is the priority encoder
]

order = [ "maincpu", "audiocpu", "k007232", "k052109", "k051960", "proms" ]
